import type { Metadata } from "next";
// Self-hosted Geist fonts. The `geist` package bundles the .woff2 files
// locally (via next/font/local), so compilation never has to download from
// fonts.gstatic.com — which avoids the Turbopack "Can't resolve
// @vercel/turbopack-next/internal/font/google/font" failure when that
// runtime download can't be established.
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
